# Generated by Django 5.2.3 on 2025-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True),
        ),
    ]
